import { z } from "zod";

const AddressSchema = z.object({
  AdditionalInfo: z.string(),
  City: z.string(),
  Country: z.string(),
  County: z.string(),
  Description: z.string(),
  Neighborhood: z.string(),
  Number: z.string(),
  PostalCode: z.string(),
  SettlementType: z.number(),
  State: z.string(),
  Street: z.string(),
});

export const ShatelMobileRemainedSchema = z.object({
  credit: z.string(),
  internet_packages: z.array(z.any()),
  internet_percent: z.array(z.string()),
  internet_used: z.string(),
  internet_used_unit: z.string(),
  sms_packages: z.array(z.any()),
  sms_percent: z.string(),
  sms_used: z.string(),
  voice_packages: z.array(z.any()),
  voice_percent: z.string(),
  voice_used: z.string(),
});

export const ShatelMobileProfileSchema = z.object({
  AcademyTitle: z.number(),
  Address: AddressSchema,
  BirthCertNumber: z.string(),
  Birthday: z.string(),
  ContactDocumenExpirationDate: z.string(),
  ContactDocumentType: z.number(),
  ContactFamilyName: z.string(),
  ContactFamilyName1: z.string(),
  ContactFamilyName2: z.string(),
  ContactFiscalId: z.string(),
  ContactName: z.string(),
  ContactPhone: z.string(),
  ContactPreference: z.number(),
  DocumentExpirationDate: z.string(),
  DocumentType: z.number(),
  EmailAddress: z.string(),
  ExternalID: z.string(),
  FiscalId: z.string(),
  Gender: z.number(),
  IdDefaultBillingAccount: z.number(),
  IdSubscriber: z.number(),
  Locale: z.string(),
  MarketingConsent: z.number(),
  Name: z.string(),
  Nationality: z.string(),
  PosID: z.string(),
  SalesChannel: z.number(),
  SalesPerson: z.string(),
  ScoringTag: z.string(),
  ScoringValue: z.number(),
  ShippingAddress: AddressSchema,
  SocialData: z.null(),
  SpecialType: z.number(),
  Status: z.number(),
  SubType: z.number(),
  SubscriberType: z.number(),
  Title: z.number(),
});

export const ShatelMobileInboxSchema = z.object({
  fiscal_id: z.string(),
  id: z.number(),
  messages: z
    .object({
      action: z.string(),
      id: z.number(),
      m_type: z.string(),
      offer_id: z.number(),
      seen: z.boolean(),
      text_ar: z.string(),
      text_en: z.string(),
      text_fa: z.string(),
      title_ar: z.string(),
      title_en: z.string(),
      title_fa: z.string(),
    })
    .array(),
  new_messages_count: z.number(),
});
