import { z } from "zod";

const AddressSchema = z.object({
	AdditionalInfo: z.string(),
	City: z.string(),
	Country: z.string(),
	County: z.string(),
	Description: z.string(),
	Neighborhood: z.string(),
	Number: z.string(),
	PostalCode: z.string(),
	SettlementType: z.number(),
	State: z.string(),
	Street: z.string(),
});

export const ProfileModel = z.object({
	AcademyTitle: z.number(),
	Address: AddressSchema,
	BirthCertNumber: z.string(),
	Birthday: z.string(),
	ContactDocumenExpirationDate: z.string(),
	ContactDocumentType: z.number(),
	ContactFamilyName: z.string(),
	ContactFamilyName1: z.string(),
	ContactFamilyName2: z.string(),
	ContactFiscalId: z.string(),
	ContactName: z.string(),
	ContactPhone: z.string(),
	ContactPreference: z.number(),
	DocumentExpirationDate: z.string(),
	DocumentType: z.number(),
	EmailAddress: z.string(),
	ExternalID: z.string(),
	FiscalId: z.string(),
	Gender: z.number(),
	IdDefaultBillingAccount: z.number(),
	IdSubscriber: z.number(),
	Locale: z.string(),
	MarketingConsent: z.number(),
	Name: z.string(),
	Nationality: z.string(),
	PosID: z.string(),
	SalesChannel: z.number(),
	SalesPerson: z.string(),
	ScoringTag: z.string(),
	ScoringValue: z.number(),
	ShippingAddress: AddressSchema,
	SocialData: z.null(),
	SpecialType: z.number(),
	Status: z.number(),
	SubType: z.number(),
	SubscriberType: z.number(),
	Title: z.number(),
});
